version: '3'

services:
  api:
    build: .
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      POSTGRES_DB_NAME: 'postgres'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_USER: 'postgres'
    links:
      - db

  db:
    image: postgres
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_USER: 'postgres'

networks:
  backend:
    driver: bridge
