# Generated by Django 2.2.7 on 2019-11-16 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_ordering_by_id_desc_for_CustomUser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Hall name')),
                ('rows_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rows count')),
                ('rows_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rows size (seats count)')),
            ],
            options={
                'verbose_name': 'Cinema hall',
                'verbose_name_plural': 'Cinema halls',
            },
        ),
    ]
