# Generated by Django 2.2.7 on 2019-11-16 09:56

from django.db import migrations


def create_default_halls(apps, schema_editor):
    Hall = apps.get_model('booking', 'Hall')
    Hall.objects.bulk_create([
        Hall(name='Small Hall',
             rows_size=5,
             rows_count=3),
        Hall(name='Medium Hall',
             rows_size=10,
             rows_count=6),
        Hall(name='Large Hall',
             rows_size=20,
             rows_count=20)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_hall'),
    ]

    operations = [
        migrations.RunPython(create_default_halls, migrations.RunPython.noop),
    ]
