# Generated by Django 2.2.7 on 2019-11-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_create_halls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-id'], 'verbose_name': 'Cinema hall', 'verbose_name_plural': 'Cinema halls'},
        ),
    ]
