# Generated by Django 2.2.7 on 2019-11-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_ordering_by_id_desc_for_Hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Hall name'),
        ),
    ]
