# Generated by Django 2.2.7 on 2019-11-16 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_unique_name_for_Hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Title')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration')),
                ('premiere_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1896)], verbose_name='Premiere Year')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-id'],
                'unique_together': {('name', 'premiere_year')},
            },
        ),
    ]
