# Generated by Django 2.2.7 on 2019-11-18 05:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=32, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Movie')),
            ],
            options={
                'verbose_name': 'Showing',
                'verbose_name_plural': 'Showings',
                'ordering': ['-time'],
                'unique_together': {('hall', 'movie', 'time')},
            },
        ),
    ]
