# Generated by Django 2.2.7 on 2019-11-18 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_showing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.Hall'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.Movie'),
        ),
    ]
