# Generated by Django 2.2.7 on 2019-11-18 11:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_Showing_time_field_to_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('row_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Row number')),
                ('seat_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Seat number in row')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.Showing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-id'],
                'unique_together': {('showing', 'row_number', 'seat_number')},
            },
        ),
    ]
